apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: bitly
  labels:
    name: database
spec:
  containers:
  - name: database
    image: mrugeshmaster/database:gcp
    imagePullPolicy: Always
    env:
      - name: mysql_server
        value: "10.168.0.7"
      - name: rabbitmq_server
        value: rabbitmq-1-rabbitmq-svc
      - name: rabbitmq_port
        value: "5672"
      - name: rabbitmq_user
        value: rabbit
      - name: rabbitmq_pass
        value: aBJ3VXVaNG3V