apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendserver-deployment
  namespace: bitly
spec:
  selector:
    matchLabels:
      name: trendserver-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: trendserver-deployment
    spec:
      containers:
      - name: trendserver-deployment
        image: mrugeshmaster/trendserver:gcp
        imagePullPolicy: Always
        env:
        - name: trend_server
          value: "10.142.0.11:9090"
        - name: rabbitmq_server
          value: rabbitmq-1-rabbitmq-svc
        - name: rabbitmq_port
          value: "5672"
        - name: rabbitmq_user
          value: rabbit
        - name: rabbitmq_pass
          value: aBJ3VXVaNG3V